### PR TITLE
nixpkgs: add xgcm

### PR DESCRIPTION
**Pull request by raboof**
quick attempt to add docrep.

this could possibly work, but I couldn't test further since I'm on
unstable and cartopy is currently marked broken there, so I'm leaving it to
CI ;)

### CODE REVIEW

**Comment by nbren12** [comment]
Thanks for the derivation. At the bottom of the README I did say this though:
> Manually packaging the <random pip package> (e.g. writing an explicit nix derivation, conda recipe, etc) is not allowed.

That said, I think it is still worthwhile to include this and let the reader judge if manual packaging is a feasible approach. It doesn't scale so well to packages with more complicated dependencies than docrep.

**Comment by nbren12** [comment]
This doesn't actually install docrep for some reason.

I actually just realized docrep is in nixpkgs....so it's not a great example.

**Comment by raboof** [comment]
> At the bottom of the README I did say this though

Ah, I stopped reading after "Nix-based tools have more leeway" I guess ;)

> It doesn't scale so well to packages with more complicated dependencies than docrep.

I don't know - of course with more complicated dependencies it becomes more complicated, but it seems to me that's where being able to 'manually package' it actually comes in useful...

> I actually just realized docrep is in nixpkgs....so it's not a great example.

(updated PR to instal xgcm)

**Comment by nbren12** [comment]
Thanks! I am leaning towards manual packaging as the more practical solution. mach-nix has solved the challenge, but only with a 40 minute build time, that will likely recur if any of the requirements change (https://discourse.nixos.org/t/python-package-rodeo/12282/12). One could probably write all the manual packages needed in that amount of time.

**Comment by nbren12** [comment]
Congrats. Looks like this works (after I fixed a small typo).

@raboof How long do you estimate it should take a moderately well-informed user (assuming they understand overrideAttrs) to write these? I'm interested in comparing the "time to solution" of this approach with the more automated tools.

**Comment by raboof** [comment]
> Congrats. Looks like this works (after I fixed a small typo).

:tada: 

> How long do you estimate it should take a moderately well-informed user (assuming they understand overrideAttrs) to write these? I'm interested in comparing the "time to solution" of this approach with the more automated tools.

I think that's pretty hard to say... the `xgcm` and `old_docrep` derivations were quite straightforward: you just add the pname/version/src and then the error messages during the build are fairly clear in telling you what else needs to happen. I wager you could write those in 10 minutes.

The `cartopy_unchecked` one was more tricky, though: the build failed running the checks, but at first I didn't realize there are both 'post-build checks' and 'post-install checks', so I spent some time figuring that out. How long that takes kinda depends on how lucky you are diagnosing the problem, so that could easily take you an hour (or not). If it turns out the check that I just suppressed here indicated a real problem, then fixing that problem might take much longer. It is worth doing though: if you can fix it, you can contribute that fix upstream and help others not have the same problem :).

I don't have much experience with the 'more automated tools' so i can't really say anything about how they compare. On the one hand I bet they do things for you to make life easier, on the other hand when they fail it may or may not be easier to diagnose...

**Pull request merged**
